version: "3"
services:  
  privateff:
    container_name: ff-private-api
    build:
      context: private
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
      AWS_DEFAULT_REGION: us-west-2
  
  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    tty: true
    depends_on:
      - privateff
